import { describe, it, expect, beforeEach, afterEach } from 'bun:test';
import { mkdirSync, writeFileSync, rmSync } from 'fs';
import { join } from 'path';
import { checkTranslations, extractKeysFromSource } from './check';

const TEST_DIR = '/tmp/ats-test-check';
const I18N_DIR = join(TEST_DIR, 'i18n');
const SRC_DIR = join(TEST_DIR, 'src');

describe('extractKeysFromSource', () => {
    it('should extract translate() calls', () => {
        const code = `const s = this.i18n.translate('common:nav.home');`;
        const { keys } = extractKeysFromSource(code);
        expect(keys).toContain('common:nav.home');
    });

    it('should extract instant() calls', () => {
        const code = `this.i18n.instant('common:greeting', { name: 'Igor' })`;
        const { keys } = extractKeysFromSource(code);
        expect(keys).toContain('common:greeting');
    });

    it('should extract pipe syntax', () => {
        const html = `<h1>{{ 'common:nav.title' | translate }}</h1>`;
        const { keys } = extractKeysFromSource(html);
        expect(keys).toContain('common:nav.title');
    });

    it('should extract select() scopes', () => {
        const code = `protected readonly common = this.i18n.select('common');`;
        const { scopes } = extractKeysFromSource(code);
        expect(scopes).toContain('common');
    });

    it('should handle multiple keys in one file', () => {
        const code = `
            const a = this.i18n.translate('common:title');
            const b = this.i18n.translate('settings:theme');
            const c = this.i18n.instant('common:greeting');
        `;
        const { keys } = extractKeysFromSource(code);
        expect(keys).toHaveLength(3);
    });

    it('should extract quoted source references and dynamic prefixes', () => {
        const code = `
            const option = { label: 'admin:orders.title' };
            const statusKey = 'admin:orders.status.' + status;
        `;
        const { keys } = extractKeysFromSource(code);
        expect(keys).toContain('admin:orders.title');
        expect(keys).toContain('admin:orders.status.');
    });
});

describe('checkTranslations', () => {
    beforeEach(() => {
        rmSync(TEST_DIR, { recursive: true, force: true });
        mkdirSync(I18N_DIR, { recursive: true });
        mkdirSync(SRC_DIR, { recursive: true });
    });

    afterEach(() => {
        rmSync(TEST_DIR, { recursive: true, force: true });
    });

    it('should detect missing keys (used in code but not in JSON)', async () => {
        writeFileSync(
            join(I18N_DIR, 'common.json'),
            JSON.stringify({ title: 'Hello' }),
        );
        writeFileSync(
            join(SRC_DIR, 'app.ts'),
            `this.i18n.translate('common:title');\nthis.i18n.translate('common:missing_key');`,
        );

        const result = await checkTranslations({ i18n: I18N_DIR, src: SRC_DIR });
        expect(result.missing).toContain('common:missing_key');
    });

    it('should detect unused keys (in JSON but not in code)', async () => {
        writeFileSync(
            join(I18N_DIR, 'common.json'),
            JSON.stringify({ title: 'Hello', unused_key: 'Never used' }),
        );
        writeFileSync(
            join(SRC_DIR, 'app.ts'),
            `this.i18n.translate('common:title');`,
        );

        const result = await checkTranslations({ i18n: I18N_DIR, src: SRC_DIR });
        expect(result.unused).toContain('common:unused_key');
    });

    it('should mark select() scope keys as used', async () => {
        writeFileSync(
            join(I18N_DIR, 'common.json'),
            JSON.stringify({ title: 'Hello', nav: { home: 'Home' } }),
        );
        writeFileSync(
            join(SRC_DIR, 'app.ts'),
            `protected readonly common = this.i18n.select('common');`,
        );

        const result = await checkTranslations({ i18n: I18N_DIR, src: SRC_DIR });
        // select('common') marks all common:* keys as used
        expect(result.unused).toHaveLength(0);
    });

    it('should report no issues when all keys are accounted for', async () => {
        writeFileSync(
            join(I18N_DIR, 'common.json'),
            JSON.stringify({ title: 'Hello' }),
        );
        writeFileSync(
            join(SRC_DIR, 'app.ts'),
            `this.i18n.translate('common:title');`,
        );

        const result = await checkTranslations({ i18n: I18N_DIR, src: SRC_DIR });
        expect(result.missing).toHaveLength(0);
        expect(result.unused).toHaveLength(0);
    });

    it('should not treat generated type unions as source usage', async () => {
        writeFileSync(
            join(I18N_DIR, 'common.json'),
            JSON.stringify({ title: 'Hello', unused: 'Unused' }),
        );
        writeFileSync(
            join(SRC_DIR, 'i18n.generated.ts'),
            `// Auto-generated by angular-translation-service CLI\nexport type TranslationKey = 'common:title' | 'common:unused';`,
        );
        writeFileSync(join(SRC_DIR, 'app.ts'), `this.i18n.translate('common:title');`);

        const result = await checkTranslations({ i18n: I18N_DIR, src: SRC_DIR });
        expect(result.unused).toContain('common:unused');
    });

    it('should validate quoted source references against every locale', async () => {
        const enDir = join(I18N_DIR, 'en');
        const ptDir = join(I18N_DIR, 'pt-BR');
        mkdirSync(enDir, { recursive: true });
        mkdirSync(ptDir, { recursive: true });
        writeFileSync(join(enDir, 'common.json'), JSON.stringify({ title: 'Hello' }));
        writeFileSync(join(ptDir, 'common.json'), JSON.stringify({}));
        writeFileSync(join(SRC_DIR, 'app.ts'), `const label = 'common:title';`);

        const result = await checkTranslations({ i18n: I18N_DIR, src: SRC_DIR });
        expect(result.referenceFailures).toContainEqual(expect.objectContaining({
            lang: 'pt-BR',
            key: 'common:title',
        }));
    });

    it('should validate dynamic prefix references by prefix match in every locale', async () => {
        const enDir = join(I18N_DIR, 'en');
        const ptDir = join(I18N_DIR, 'pt-BR');
        mkdirSync(enDir, { recursive: true });
        mkdirSync(ptDir, { recursive: true });
        writeFileSync(join(enDir, 'admin.json'), JSON.stringify({ orders: { status: { open: 'Open' } } }));
        writeFileSync(join(ptDir, 'admin.json'), JSON.stringify({ orders: { status: { open: 'Aberto' } } }));
        writeFileSync(join(SRC_DIR, 'app.ts'), `const key = 'admin:orders.status.' + status;`);

        const result = await checkTranslations({ i18n: I18N_DIR, src: SRC_DIR });
        expect(result.referenceFailures).toHaveLength(0);
        expect(result.missing).not.toContain('admin:orders.status.');
        expect(result.unused).toHaveLength(0);
    });

    it('should report dynamic prefixes that match no keys in a locale', async () => {
        const enDir = join(I18N_DIR, 'en');
        const ptDir = join(I18N_DIR, 'pt-BR');
        mkdirSync(enDir, { recursive: true });
        mkdirSync(ptDir, { recursive: true });
        writeFileSync(join(enDir, 'admin.json'), JSON.stringify({ orders: { status: { open: 'Open' } } }));
        writeFileSync(join(ptDir, 'admin.json'), JSON.stringify({ orders: { label: 'Pedidos' } }));
        writeFileSync(join(SRC_DIR, 'app.ts'), `const key = 'admin:orders.status.' + status;`);

        const result = await checkTranslations({ i18n: I18N_DIR, src: SRC_DIR });
        expect(result.referenceFailures).toContainEqual(expect.objectContaining({
            lang: 'pt-BR',
            key: 'admin:orders.status.',
            isPrefix: true,
        }));
    });

    it('should report cross-locale parity failures in both directions', async () => {
        const enDir = join(I18N_DIR, 'en');
        const ptDir = join(I18N_DIR, 'pt-BR');
        mkdirSync(enDir, { recursive: true });
        mkdirSync(ptDir, { recursive: true });
        writeFileSync(join(enDir, 'common.json'), JSON.stringify({ title: 'Hello', subtitle: 'World' }));
        writeFileSync(join(ptDir, 'common.json'), JSON.stringify({ title: 'Olá', orphan: 'Extra' }));

        const result = await checkTranslations({ i18n: I18N_DIR, src: SRC_DIR });
        expect(result.parityFailures).toContainEqual({
            lang: 'pt-BR',
            namespace: 'common',
            key: 'subtitle',
            type: 'missing',
        });
        expect(result.parityFailures).toContainEqual({
            lang: 'pt-BR',
            namespace: 'common',
            key: 'orphan',
            type: 'extra',
        });
    });

    it('should report empty values across locales', async () => {
        const enDir = join(I18N_DIR, 'en');
        const ptDir = join(I18N_DIR, 'pt-BR');
        mkdirSync(enDir, { recursive: true });
        mkdirSync(ptDir, { recursive: true });
        writeFileSync(join(enDir, 'common.json'), JSON.stringify({ title: 'Hello' }));
        writeFileSync(join(ptDir, 'common.json'), JSON.stringify({ title: '' }));

        const result = await checkTranslations({ i18n: I18N_DIR, src: SRC_DIR });
        expect(result.emptyValues).toContainEqual({
            lang: 'pt-BR',
            namespace: 'common',
            key: 'title',
        });
    });
});
