/**
 * ats generate — Generate TypeScript interfaces from JSON translation files
 *
 * Ported from: duo-fusion-next/scripts/generate-i18n-types.ts
 */

import { readdirSync, readFileSync, writeFileSync, existsSync } from 'fs';
import { join, basename, resolve } from 'path';

interface GenerateOptions {
    input: string;
    output: string;
    check?: boolean;
}

export async function generateTypes(options: GenerateOptions): Promise<void> {
    const inputDir = resolve(options.input);
    const outputFile = resolve(options.output);

    if (!existsSync(inputDir)) {
        console.error(`❌ Input directory not found: ${inputDir}`);
        process.exit(1);
    }

    console.log('🔄 Generating i18n types...');
    console.log(`   Input:  ${inputDir}`);
    console.log(`   Output: ${outputFile}`);

    const files = readdirSync(inputDir).filter((f) => f.endsWith('.json'));

    if (files.length === 0) {
        console.error(`❌ No JSON files found in ${inputDir}`);
        process.exit(1);
    }

    const namespaces: string[] = [];
    const typeDefinitions: string[] = [];
    const flatKeyDefinitions: string[] = [];

    for (const file of files) {
        const namespace = basename(file, '.json');
        namespaces.push(namespace);

        const content = JSON.parse(readFileSync(join(inputDir, file), 'utf-8'));
        const typeDef = generateTypeDefinition(content);
        const flatKeys = collectFlatKeys(content, namespace);

        const nsKey = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(namespace)
            ? namespace
            : `'${namespace}'`;

        typeDefinitions.push(`  ${nsKey}: ${typeDef};`);

        const keyLiterals = flatKeys.map((k) => `'${k}'`).join(' | ') || 'never';
        flatKeyDefinitions.push(`  ${nsKey}: ${keyLiterals};`);
    }

    const output = `// Auto-generated by @angular-translation-service/cli
// Do not edit manually. Run: npx ats generate

export const I18N_NAMESPACES = [
${namespaces.map((n) => `  '${n}',`).join('\n')}
] as const;

export type I18nNamespace = typeof I18N_NAMESPACES[number];

export interface I18nTypes {
${typeDefinitions.join('\n')}
}

export interface I18nKeys {
${flatKeyDefinitions.join('\n')}
}

export type I18nTranslationKey = I18nKeys[keyof I18nKeys];

export type TranslationKey = I18nTranslationKey;

declare module '@angular-translation-service/core' {
  interface TranslationKeyRegistry {
    keys: I18nTranslationKey;
    namespaces: I18nTypes;
  }
}
`;

    if (options.check) {
        // CI mode: assert file is in sync
        if (!existsSync(outputFile)) {
            console.error('❌ Generated types file does not exist. Run: npx ats generate');
            process.exit(1);
        }
        const existing = readFileSync(outputFile, 'utf-8');
        if (existing !== output) {
            console.error('❌ Generated types are out of sync with JSON source. Run: npx ats generate');
            process.exit(1);
        }
        console.log('✅ Types are in sync.');
        return;
    }

    writeFileSync(outputFile, output);
    console.log(`✅ Generated ${outputFile}`);
    console.log(`   ${namespaces.length} namespaces found.`);
}

function collectFlatKeys(obj: unknown, prefix: string): string[] {
    if (typeof obj !== 'object' || obj === null) return [];
    const keys: string[] = [];
    for (const [key, value] of Object.entries(obj)) {
        const fullKey = `${prefix}:${key}`;
        if (typeof value === 'string') {
            keys.push(fullKey);
        } else if (typeof value === 'object' && value !== null) {
            keys.push(...collectFlatKeys(value, `${prefix}:${key}`).map((k) =>
                k.replace(`${prefix}:${key}:`, `${prefix}:${key}.`),
            ));
        }
    }
    return keys;
}

function generateTypeDefinition(obj: unknown, indent = 4): string {
    if (typeof obj !== 'object' || obj === null) return 'string';

    const lines: string[] = [];
    const spaces = ' '.repeat(indent);

    for (const [key, value] of Object.entries(obj)) {
        const propName = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key)
            ? key
            : `'${key}'`;

        if (typeof value === 'string') {
            lines.push(`${spaces}${propName}: string;`);
        } else {
            lines.push(`${spaces}${propName}: ${generateTypeDefinition(value, indent + 2)};`);
        }
    }

    return `{\n${lines.join('\n')}\n${' '.repeat(indent - 2)}}`;
}
