#!/usr/bin/env bun
/**
 * Pre-build step: reads all JS module files from ui/js/ and generates
 * a TypeScript file that exports them as string constants.
 *
 * This ensures the JS modules are embedded in the bundle at build time
 * instead of being loaded from disk at runtime (which breaks npm publish).
 */

import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const UI_JS_DIR = join(__dirname, '../src/commands/editor/ui/js');
const OUTPUT_FILE = join(__dirname, '../src/commands/editor/ui/js-modules.generated.ts');

const MODULE_NAMES = [
    'helpers.js',
    'state.js',
    'api.js',
    'dropdown.js',
    'render.js',
    'panels.js',
    'events.js',
    'llm.js',
];

let output = `/**
 * AUTO-GENERATED — Do not edit manually.
 * Generated by: bun packages/cli/scripts/bundle-js-modules.ts
 *
 * Contains the editor UI JavaScript modules as string constants so they
 * get bundled into the CLI dist instead of relying on runtime filesystem reads.
 */

`;

for (const name of MODULE_NAMES) {
    const content = readFileSync(join(UI_JS_DIR, name), 'utf-8');
    const varName = name.replace('.js', '').replace(/-/g, '_').toUpperCase();
    output += `export const ${varName} = ${JSON.stringify(content)};\n\n`;
}

output += `export const JS_MODULE_MAP: Record<string, string> = {\n`;
for (const name of MODULE_NAMES) {
    const varName = name.replace('.js', '').replace(/-/g, '_').toUpperCase();
    output += `    '${name}': ${varName},\n`;
}
output += `};\n`;

writeFileSync(OUTPUT_FILE, output);
console.log(`✓ Generated ${OUTPUT_FILE} (${MODULE_NAMES.length} modules)`);
